### ISSUE TITLE
Fuzzy matching should ignore current cursor position

### ISSUE THREAD

**Issue by tom-anders** [rlane/pounce.nvim#16]
If I have something like
```
test
|test 
test
```
with "|" being my cursor, then typing `stest` will match the position that my cursor is already on, which isn't really helpful IMO.

**Comment by rlane** [comment]
Good idea. Do you want to send a pull request? Otherwise I can add that.

**Comment by tom-anders** [comment]
Haven't taken a look at the code yet, I'd really appreciate if you added it :)
