### ISSUE TITLE
Pounce freezes after using telescope

### ISSUE THREAD

**Issue by giluis** [rlane/pounce.nvim#17]
When using telescope (e.g. `require('telescope.builtin').find_files()` ), if I press `<Esc>` to go into normal mode in the telescope window, and then `s` the start Pounce, It works normally.  
However, some issues:
1- It also considers matches in the buffer I was in before opening the telescope floating window (here, I pressed "pl")
![image](https://user-images.githubusercontent.com/52404649/150972836-15ae63e6-4b03-458e-83f1-c8af98a9b857.png)

2- When I press "J" , for example, I get this error: 
![image](https://user-images.githubusercontent.com/52404649/150973055-b9ea121b-1299-402e-b3e5-063597f16a5f.png)

As you see, the "pl" in plugins on line 3 still selected. And it won't disappear, not matter what I do. Even if I press the "N", it doesn't disappear. I can freely move the cursor, and it stays there. When I quit NeoVim and start it again, it's gone

Now, I don't really want to use pounce in a telescope window. In fact, I discovered this on accident.
But I figured I'd let you know about this behaviour.

Anyway, thank you for this awesome plugin! I'm loving it

**Comment by rlane** [comment]
Thanks, fixed in #19. There were some types of windows (like Telescope) that would cause an error if we tried to switch to them.
