### ISSUE TITLE
Accept empty arguments for setup function

### ISSUE THREAD

**Issue by ignamartinoli** [rlane/pounce.nvim#22]
Calling the funcion `require 'pounce'.setup()` yields an error of expected table.
For what I observed doing that is usually it's the way to initialize a plugin without custom options so it should be possible to call that function like that

**Comment by ggandor** [comment]
Pounce doesn't need to be initialized, `setup` is just a covenience function to update the settings (i.e., it's optional), so it totally makes sense to expect a table.

**Comment by ignamartinoli** [comment]
I didn't knew that. You're right, it makes sense, I thought it needed to be initialized
