### ISSUE TITLE
cmdheight=0 option necessitates having to press enter to confirm choice

### ISSUE THREAD

**Issue by benfrain** [rlane/pounce.nvim#29]
I don't think I have imagined this? Wasn't it possible to jump to the best match previously by just typing the relevant key?

Is there a way to turn off the need to press enter?

**Comment by rlane** [comment]
There shouldn't be a need to press Enter (I just tested it). What OS, Neovim version, and Pounce version are you using?

**Comment by benfrain** [comment]
NVIM v0.8.0-dev-915-g2bed0d1d9 (Got it from homebrew --HEAD couple of days ago)

macOS 12.4

Latest pounce

Wonder if it is anything to do with having the new option for `cmdheight = 0` https://github.com/neovim/neovim/pull/16251 ??

**Comment by benfrain** [comment]
Hmmm, yep, seems to be the cmdheight option. Works fine if I disable that. Amended issue title to match problem

**Comment by rlane** [comment]
Could you try #30 and let me know if that works for you? It temporarily sets cmdheight=1 so pounce can write its prompt.

**Comment by benfrain** [comment]
Yes, that works great, thanks 🙏
