### ISSUE TITLE
Feature request: Implement ;

### ISSUE THREAD

**Issue by jdelkins** [rlane/pounce.nvim#3]
This package is very cool! Love the simple approach. if only you could implement a map for `;` (or a command that could be mapped to `;`) that would take you to the next match (ideally in the direction established by the original motion), This would be a pretty much feature complete as far as I'm concerned.

**Comment by rlane** [comment]
I see [Sneak](1) handles this by temporarily remapping `f F t T ; ,`. I would like to add a "repeat" feature but maybe not something that invasive.

[1]: https://github.com/justinmk/vim-sneak/blob/94c2de47ab301d476a2baec9ffda07367046bec9/plugin/sneak.vim#L287

I pushed #4 which adds `:PounceRepeat`, can you see if that works for you?

**Comment by jdelkins** [comment]
Works great, many thanks!
